### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [TaniaMackey/prj-rev-bwfs-dasmoto#5]
https://github.com/TaniaMackey/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L2

Consider using the universal selector `*` to apply a style by default to every element and remove the repetition from the rest of your CSS rules.

```css
* {
  font-family: Helvetica;
}
```
